### ISSUE TITLE
arch issue

### ISSUE THREAD

**Issue by andrewpedia** [asifakonjee/Hyprland#2]
:: kvantum and kvantum-qt5-git are in conflict. Remove kvantum-qt5-git? [y/N]

**Comment by asifakonjee** [comment]
No, don't need to install kvantum now.

**Comment by andrewpedia** [comment]
how to increase the screen brightness ,thanks

**Comment by andrewpedia** [comment]
➜  ~ rofi -show drun

(process:19540): Rofi-WARNING **: : Failed to set locale.

can you help with this ?
thanks

**Comment by asifakonjee** [comment]
Set locale according to arch wiki: https://wiki.archlinux.org/title/locale

**Comment by andrewpedia** [comment]
how to lock the screen

**Comment by asifakonjee** [comment]
My request is that please read Hyprland wiki. You can get many informations there.

I use 7 workspaces. But you can add them in the keybind.conf

Please read the keybind.conf and you will get your answer there.
